language: python
python:
- '2.7'
install:
- pip install -r requirements/test.txt
- pip install coveralls
script: 
- ./manage.py migrate
- coverage run --source='.' manage.py test
after_success:
- coveralls